# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('sentiment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compound', models.IntegerField(null=True)),
                ('positive', models.IntegerField(null=True)),
                ('negative', models.IntegerField(null=True)),
                ('neutral', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_sentiment',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='title_sentiment',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Comment'),
        ),
    ]
